import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Aside from "./components/Aside";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.className}`}>
      <body>
        <Header />
        <div className="flex flex-col min-h-screen">
          <main className="flex-1 grid grid-cols-12 gap-6 p-6">
            {children}
          <aside className="col-span-4">
            <Aside />
          </aside>
          </main>
        </div>
      </body>
    </html>
  );
}
