// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  community: dynamic(() => import("./Community")),
  hero: dynamic(() => import("./Hero")),
  talking_points: dynamic(() => import("./TalkingPoints")),
};
